BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "frequency" (
	"id"	INTEGER NOT NULL,
	"daily"	INTEGER NOT NULL DEFAULT 1,
	"weekly"	INTEGER NOT NULL DEFAULT 2,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "alr_used" (
	"id"	INTEGER NOT NULL UNIQUE,
	"id_user"	INTEGER NOT NULL,
	"id_phrase"	INTEGER NOT NULL,
	"date"	DATETIME NOT NULL,
	FOREIGN KEY("id_phrase") REFERENCES "phrase"("id"),
	FOREIGN KEY("id_user") REFERENCES "users"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"email"	TEXT NOT NULL UNIQUE,
	"themes"	TEXT DEFAULT 1,
	"frequency"	INTEGER DEFAULT 1,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "themes" (
	"id"	INTEGER NOT NULL UNIQUE,
	"theme_name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "phrase" (
	"id"	INTEGER NOT NULL UNIQUE,
	"phrase_text"	TEXT NOT NULL UNIQUE,
	"id_theme"	INTEGER NOT NULL,
	FOREIGN KEY("id_theme") REFERENCES "themes"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
