BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "frequency" (
	"id"	INTEGER NOT NULL,
	"daily"	INTEGER NOT NULL DEFAULT 1,
	"weekly"	INTEGER NOT NULL DEFAULT 2,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "alr_used" (
	"id"	INTEGER NOT NULL UNIQUE,
	"id_user"	INTEGER NOT NULL,
	"id_phrase"	INTEGER NOT NULL,
	"date"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("id_phrase") REFERENCES "phrase"("id"),
	FOREIGN KEY("id_user") REFERENCES "users"("id")
);
CREATE TABLE IF NOT EXISTS "themes" (
	"id"	INTEGER NOT NULL UNIQUE,
	"theme_name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "phrase" (
	"id"	INTEGER NOT NULL UNIQUE,
	"phrase_text"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"email"	TEXT NOT NULL UNIQUE,
	"frequency"	INTEGER DEFAULT 1,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "phrase_themes" (
	"phrase_id"	INTEGER NOT NULL,
	"theme_id"	INTEGER NOT NULL,
	PRIMARY KEY("phrase_id","theme_id"),
	FOREIGN KEY("theme_id") REFERENCES "themes"("id"),
	FOREIGN KEY("phrase_id") REFERENCES "phrase"("id")
);
CREATE TABLE IF NOT EXISTS "user_themes" (
	"user_id"	INTEGER NOT NULL,
	"theme_id"	INTEGER NOT NULL,
	PRIMARY KEY("user_id","theme_id"),
	FOREIGN KEY("user_id") REFERENCES "users"("id"),
	FOREIGN KEY("theme_id") REFERENCES "themes"("id")
);
COMMIT;
